{
    parserClass="com.fooock.solidity.lang.parser.SolidityParser"
    classHeader="header.txt"
    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="Solidity"
    psiImplClassSuffix="Impl"
    psiPackage="com.fooock.solidity.lang.psi"
    psiImplPackage="com.fooock.solidity.lang.psi.impl"

    elementTypeHolderClass="com.fooock.solidity.lang.psi.SolidityTypes"
    elementTypeClass="com.fooock.solidity.lang.psi.SolidityElementType"
    tokenTypeClass="com.fooock.solidity.lang.psi.SolidityTokenType"

    tokens = [
        LBRACE             = '{'
        RBRACE             = '}'
        LBRACK             = '['
        RBRACK             = ']'
        LPAREN             = '('
        RPAREN             = ')'
        COLON              = ':'
        SEMICOLON          = ';'
        COMMA              = ','
        EQ                 = '=='
        ASSIGN             = '='
        NOT_EQ             = '!='
        NOT                = '!'
        PLUS_PLUS          = '++'
        PLUS_ASSIGN        = '+='
        PLUS               = '+'
        MINUS_MINUS        = '--'
        MINUS_ASSIGN       = '-='
        MINUS              = '-'
        COND_OR            = '||'
        BIT_OR_ASSIGN      = '|='
        COND_AND           = '&&'
        BIT_AND_ASSIGN     = '&='
        BIT_AND            = '&'
        BIT_OR             = '|'
        SHIFT_LEFT_ASSIGN  = '<<='
        SHIFT_LEFT         = '<<'
        LESS_OR_EQUAL      = '<='
        LESS               = '<'
        BIT_XOR_ASSIGN     = '^='
        BIT_XOR            = '^'
        MUL_ASSIGN         = '*='
        MUL                = '*'
        QUOTIENT_ASSIGN    = '/='
        QUOTIENT           = '/'
        REMAINDER_ASSIGN   = '%='
        REMAINDER          = '%'
        SHIFT_RIGHT_ASSIGN = '>>='
        SHIFT_RIGHT        = '>>'
        GREATER_OR_EQUAL   = '>='
        GREATER            = '>'
        SPACE              = 'regex:\s+'
    ]
}

